FROM mysql/mysql-server:latest as base

VOLUME /var/lib/mysql

ENV MYSQL_ROOT_PASSWORD=root_paswd
ENV MYSQL_ROOT_HOST=% 
ENV MYSQL_USER=db_user 
ENV MYSQL_PASSWORD=qwe123
ENV MYSQL_DATABASE=strapi-cdn

EXPOSE 3306 
